Repository assistancechat/assistance.chat, pull requests merged in 2023-02, with the labels that each got.

#67 Mini browser extension
  .vscode/launch.json
  .vscode/workspace.code-workspace
  src/typescript/browser-extensions/assistance/.gitignore
  src/typescript/browser-extensions/assistance/LICENSE
  src/typescript/browser-extensions/assistance/README.md
  src/typescript/browser-extensions/assistance/background.html
  src/typescript/browser-extensions/assistance/background.ts
  src/typescript/browser-extensions/assistance/index.html
  src/typescript/browser-extensions/assistance/loader/extension-injector.js
  src/typescript/browser-extensions/assistance/loader/gmail-js-loader.js
  src/typescript/browser-extensions/assistance/manifest.json
  src/typescript/browser-extensions/assistance/package-lock.json
  src/typescript/browser-extensions/assistance/package.json
  src/typescript/browser-extensions/assistance/postcss.config.cjs
  src/typescript/browser-extensions/assistance/public/logo128.png
  src/typescript/browser-extensions/assistance/public/manifest.json
  src/typescript/browser-extensions/assistance/public/manifestv3.json
  src/typescript/browser-extensions/assistance/renovate.json
  src/typescript/browser-extensions/assistance/src/App.tsx
  src/typescript/browser-extensions/assistance/src/img/brain.svg
  src/typescript/browser-extensions/assistance/src/index.css
  src/typescript/browser-extensions/assistance/src/index.tsx
  src/typescript/browser-extensions/assistance/src/main.ts
  src/typescript/browser-extensions/assistance/src/style.css
  src/typescript/browser-extensions/assistance/src/types.d.ts
  src/typescript/browser-extensions/assistance/src/vite-env.d.ts
  src/typescript/browser-extensions/assistance/tailwind.config.cjs
  src/typescript/browser-extensions/assistance/tsconfig.json
  src/typescript/browser-extensions/assistance/tsconfig.node.json
  src/typescript/browser-extensions/assistance/vite.chrome.config.ts
  src/typescript/browser-extensions/assistance/vite.config.ts
  src/typescript/browser-extensions/assistance/vite.content.config.ts
Labels: 20 min review

#79 added google analytics to pages/_app.tsx
  examples/student.assistance.chat/package-lock.json
  examples/student.assistance.chat/package.json
  examples/student.assistance.chat/src/components/Common.tsx
  examples/student.assistance.chat/src/pages/_app.tsx
Labels: 5 min review

#80 changed prop type in common to any, updated counselling.json, updated…
  examples/student.assistance.chat/src/components/Common.tsx
  examples/student.assistance.chat/src/data/counselling.json
  examples/student.assistance.chat/src/data/education.json
  examples/student.assistance.chat/src/pages/Counselling.tsx
Labels: 5 min review

#82 Youtube video fix
  examples/student.assistance.chat/src/data/general.json
Labels: 1 min review

#86 changed backgrounds of agedcare, changed enrolment form
  examples/student.assistance.chat/src/components/NavBar.tsx
  examples/student.assistance.chat/src/data/agedCare.json
Labels: 5 min review

#89 added speak to an interviewer now, changed chat modal to reflect the …
  examples/student.assistance.chat/src/components/ChatModal.tsx
  examples/student.assistance.chat/src/providers/chat.ts
Labels: 5 min review
